weights: ' '
cfg: /kaggle/working/Efficient-net/models/yolov5s-effiecientNet-Cbam.yaml
data: /kaggle/working/Efficient-net/fire-detection-FM-1/data.yaml
hyp: /kaggle/working/Efficient-net/data/hyps/hyp.scratch-low.yaml
epochs: 300
batch_size: 64
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: yolov5sCustom-EfficntNet-CBAM
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 60
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolov5sCustom-EfficntNet-CBAM
